<?php 


return array(
	'kanban' => __('Kanban'),
	'task_deleted' => __('{0} deleted the task'),
	'task_restore' => __('Task deleted. <u>Undo</u>?'),
	'task_undeleted' => __('{0} restored the deleted task'),
	'task_updates' => __('Your tasks have been synced.'),
	'task_added_to_project' => __('{0} added the task to the project "{1}"'),
	'task_removed_from_project' => __('{0} removed the task project'),
	'task_added_error' => __('There was an error adding a task'),
	'task_save_error' => __('There was an error saving that task'),
	'task_delete_error' => __('There was an error deleting that task'),
	'task_added_to_project_previous' => __(' (previously "{0}")'),
	'task_moved_to_status' => __('{0} moved the task to "{1}"'),
	'task_moved_to_status_previous' => __(' (previously "{0}")'),
	'task_moved_to_position' => __('{0} reordered the task to "{1}"'),
	'task_moved_to_position_previous' => __(' (previously "{0}")'),
	'task_title_updated' => __('{0} updated the task title to "{1}"'),
	'task_title_updated_previous' => __(' (previously "{0}")'),
	'task_assigned_to' => __('{0} assigned the task to {1}'),
	'task_assigned_to_previous' => __(' (previously "{0}")'),
	'task_estimate_updated' => __('{0} set the task estimate to "{1}"'),
	'task_estimate_updated_previous' => __(' (previously "{0}")'),
	'project_added' => __('{0} added the project "{1}"'),
	'project_updated' => __('{0} updated the project title "{1}"'),
	'project_updates' => __('Your projects have been synced.'),
	'project_delete' => __('{0} deleted the project "{1}"'),
	'project_delete_confirm' => __('Are you sure you want to delete this project?'),
	'status_empty_confirm' => __('Are you sure you want to delete all tasks in this column?'),
	'status_wip_task_limit_error' => __('The WIP (Work In Progress) limit has been reached.'),
); // no trailing slash